module DefinitionHelper

  def getOSOptions
    list = {
      0  => "Linux: Amazon Linux",
      1  => "Linux: Android",
      2  => "Linux: Arch Linux",
      3  => "Linux: Backtrack",
      4  => "Linux: CentOS",
      5  => "Linux: Chrome OS",
      6  => "Linux: Chromium OS",
      7  => "Linux: Chakra",
      8  => "Linux: Crunchbang",
      9  => "Linux: Debian",
      10 => "Linux: Fedora",
      11 => "Linux: Firefox OS",
      12 => "Linux: Gentoo",
      13 => "Linux: Kubuntu",
      14 => "Linux: Linux From Scratch",
      15 => "Linux: Linux Mint",
      16 => "Linux: Linux Mint Debian",
      17 => "Linux: Linux Mint KDE",
      18 => "Linux: Lubuntu",
      19 => "Linux: Mandriva",
      20 => "Linux: OpenSUSE",
      21 => "Linux: Oracle Enterprise Linux",
      22 => "Linux: Other",
      23 => "Linux: PCLinuxOS",
      24 => "Linux: RHEL",
      25 => "Linux: Sabayon",
      26 => "Linux: Scientific Linux",
      27 => "Linux: Slackware",
      28 => "Linux: SLES",
      29 => "Linux: Ubuntu",
      30 => "Linux: Xubuntu",
      31 => "Mac OS X: OS X 10.9 (Mavericks)",
      32 => "Mac OS X: OS X 10.8 (Mountain Lion)",
      33 => "Mac OS X: Mac OS X 10.7 (Lion)",
      34 => "Mac OS X: Mac OS X 10.6 (Snow Leopard, including server edition)",
      35 => "Mac OS X: Mac OS X 10.5 (Leopard, including server edition)",
      36 => "Mac OS X: Mac OS X 10.4 (Tiger, including server edition)",
      37 => "Mac OS X: Mac OS X 10.3 (Panther, including server edition)",
      38 => "Mac OS X: Mac OS X 10.2 (Jaguar, including server edition)",
      39 => "Mac OS X: Mac OS X 10.1 (Puma, including server edition)",
      40 => "Mac OS X: Mac OS X 10.0 (Cheetah, including server edition)",
      41 => "Unix: AIX",
      42 => "Unix: BSD",
      43 => "Unix: HPUX",
      44 => "Unix: Solaris",
      45 => "Unix: Xenix",
      46 => "Windows: Windows 8.1",
      47 => "Windows: Windows 8",
      48 => "Windows: Windows 7",
      49 => "Windows: Windows Vista",
      50 => "Windows: Windows XP",
      51 => "Windows: Windows ME",
      52 => "Windows: Windows 2000",
      53 => "Windows: Windows 98",
      54 => "Windows: Windows NT 4.0",
      55 => "Windows: Windows 95",
      56 => "Windows: Windows Server 2012 R2",
      57 => "Windows: Windows Server 2012",
      58 => "Windows: Windows Server 2008 R2",
      59 => "Windows: Windows Server 2008",
      60 => "Windows: Windows Server 2003",
      61 => "Other",
      62 => "No Preference / Not Applicable"
    }
  end

  def getLanguageOptions
    list = {
      0  => "ABAP",
      1  => "ActionScript",
      2  => "Ada",
      3  => "Assembly",
      4  => "C",
      5  => "C shell",
      6  => "C#",
      7  => "C++",
      8  => "COBOL",
      9  => "Common Lisp",
      10 => "cT",
      11 => "D",
      12 => "Delphi/Object Pascal",
      13 => "Emacs Lisp",
      14 => "F#",
      15 => "Fortran",
      16 => "Go",
      17 => "Haskell",
      18 => "J#",
      19 => "Java",
      20 => "JavaScript",
      21 => "Ladder Logic",
      22 => "Lisp",
      23 => "Logo",
      24 => "Lua",
      25 => "MATLAB",
      26 => "Max/MSP",
      27 => "ML",
      28 => "Moto",
      29 => "Objective-C",
      30 => "OpenEdge ABL",
      31 => "Pascal",
      32 => "Perl",
      33 => "PHP",
      34 => "PL/I",
      35 => "PL/SQL",
      36 => "PostScript",
      37 => "Prolog",
      38 => "Python",
      39 => "R",
      40 => "RPG (OS/400)",
      41 => "Ruby",
      42 => "SAS",
      43 => "Scala",
      44 => "Scratch",
      45 => "Tcl",
      46 => "Transact-SQL",
      47 => "Visual Basic",
      48 => "Visual Basic .NET",
      49 => "Z shell",
      50 => "Other",
      51 => "None / Not Applicable"
    }
  end

  def getAgeOptions
    list = {
      0 => "0-14",
      1 => "15-24",
      2 => "25-44",
      3 => "45-64",
      4 => "65+"
    }
  end

  def getEducationOptions
    list = {
      0 => "No/some college (no degree)",
      1 => "Associate’s degree (including occupational or academic degrees)",
      2 => "Bachelor’s degree (BA, BS, AB, etc)",
      3 => "Master’s degree (MA, MS, MENG, MSW, etc)",
      4 => "Professional school degree (MD, DDC, JD, etc)",
      5 => "Doctorate degree (PhD, EdD, etc)"
    }
  end
end
