module DefinitionHelper

  def getOSOptions
    list = {
      0  => "Linux: Amazon Linux",
      1  => "Linux: Android",
      2  => "Linux: Arch Linux",
      3  => "Linux: Backtrack",
      4  => "Linux: CentOS",
      5  => "Linux: Chrome OS",
      6  => "Linux: Chromium OS",
      7  => "Linux: Chakra",
      8  => "Linux: Crunchbang",
      9  => "Linux: Debian",
      10 => "Linux: Fedora",
      11 => "Linux: Firefox OS",
      12 => "Linux: Gentoo",
      13 => "Linux: Kubuntu",
      14 => "Linux: Linux From Scratch",
      15 => "Linux: Linux Mint",
      16 => "Linux: Linux Mint Debian",
      17 => "Linux: Linux Mint KDE",
      18 => "Linux: Lubuntu",
      19 => "Linux: Mandriva",
      20 => "Linux: OpenSUSE",
      21 => "Linux: Oracle Enterprise Linux",
      22 => "Linux: Other",
      23 => "Linux: PCLinuxOS",
      24 => "Linux: RHEL",
      25 => "Linux: Sabayon",
      26 => "Linux: Scientific Linux",
      27 => "Linux: Slackware",
      28 => "Linux: SLES",
      29 => "Linux: Ubuntu",
      30 => "Linux: Xubuntu",
      31 => "Mac OS X: OS X 10.9 (Mavericks)",
      32 => "Mac OS X: OS X 10.8 (Mountain Lion)",
      33 => "Mac OS X: Mac OS X 10.7 (Lion)",
      34 => "Mac OS X: Mac OS X 10.6 (Snow Leopard, including server edition)",
      35 => "Mac OS X: Mac OS X 10.5 (Leopard, including server edition)",
      36 => "Mac OS X: Mac OS X 10.4 (Tiger, including server edition)",
      37 => "Mac OS X: Mac OS X 10.3 (Panther, including server edition)",
      38 => "Mac OS X: Mac OS X 10.2 (Jaguar, including server edition)",
      39 => "Mac OS X: Mac OS X 10.1 (Puma, including server edition)",
      40 => "Mac OS X: Mac OS X 10.0 (Cheetah, including server edition)",
      41 => "Windows: Windows 8.1",
      42 => "Windows: Windows 8",
      43 => "Windows: Windows 7",
      44 => "Windows: Windows Vista",
      45 => "Windows: Windows XP",
      46 => "Windows: Windows ME",
      47 => "Windows: Windows 2000",
      48 => "Windows: Windows 98",
      49 => "Windows: Windows NT 4.0",
      50 => "Windows: Windows 95",
      51 => "Windows: Windows Server 2012 R2",
      52 => "Windows: Windows Server 2012",
      53 => "Windows: Windows Server 2008 R2",
      54 => "Windows: Windows Server 2008",
      55 => "Windows: Windows Server 2003"
    }
  end
end
